### ISSUE TITLE
Move over System/ and System2/ images from Testgame

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/RTP#13]
Problem:
```
System/ system1-4.png and Royal.png by andwhyisit (License: CC BY-SA 3.0)
System2/ files by andwhyisit (License: CC BY-SA 3.0)
```

**Comment by fdelapena** [comment]
Hi @andwhyisit, I guess you made this RTP replacement contribution years ago via old project forums. Thanks again for your contribution.

After some time, we considered Creative Commons Attribution (CC-BY) license is more suitable for non-CC licensed games. Most classic RPG Maker  games have mixed custom licenses and might collide with CC BY-SA licensing when replacing or customizing them. To prevent this, all new assets are using CC-BY 4.0, OGA-BY 3.0 or CC0, if you want to change the license for the mentioned assets in this issue thread. If you want to confirm a license change for your assets, it would help a lot to advance the RTP replacement project.

**Comment by andwhyisit** [comment]
OGA-BY 3.0 sounds alright. I'll switch to that.

**Comment by fdelapena** [comment]
Thanks @andwhyisit! Because existing OGA-BY assets (Panorama files by Tom) are also CC-BY 4.0, I'd suggest you to publish under both licenses, to keep the [README.md](https://github.com/EasyRPG/RTP/blob/master/README.md) detailing the same common license for all assets, even when there are assets with multiple licenses. Per-file license details are mentioned in the [AUTHORS.md](https://github.com/EasyRPG/RTP/blob/master/AUTHORS.md) document.

**Comment by andwhyisit** [comment]
Alright... consider it to be under both licences then.
