### ISSUE TITLE
Soundimage (free audio)

### ISSUE THREAD

**Issue by Zefk** [EasyRPG/RTP#14]
@carstene1ns 
I think this site could cover all the free audio needs.

Free Music, Sound Effects and Images for Your Projects by Eric Matyas.
http://soundimage.org/

**Comment by Ghabry** [comment]
Thanks for your contribution but because the "RTP" is a general purpose collection of assets & audio for any type of RPG the license is too restrictive. Also the attribution part with mentioning in the credits screen is problematic because probably almost all games would violate these clauses by accident.
"My license is exactly the same as CC by Attribution 4.0 with one restriction: The use of my music in any media that violates Youtube community standards is prohibited. In other words, you can’t use my music in obscene material. Please see my “About” page for the full license."
