### ISSUE TITLE
a CC BY NC version?

### ISSUE THREAD

**Issue by pirate486743186** [EasyRPG/RTP#21]
This seams to have stalled for many years. What if you had a noncommercial version?

This way, it will be easier to harvest assets that are already created. It would be legally compatible with +90% of games. This is meant to be a second version, not a replacement to this one. It's a more pragmatic solution, in order to actually have something usable in a timely manner.

**Comment by rohkea** [comment]
I believe it's stalled not because we don't have resources (we do! there's plenty of CC-BY resources on OpenGameArt that can be adapted), but because no one is working on it right now.

If you're willing to start a non-commercial RTP, you can start collecting it. You can start working on it in your repository, you don't need anyone's permission for that. You can even clone this repository as a starting point.

If you suggest that someone else does it, then I don't think there are any volunteers right now.

**Comment by Ghabry** [comment]
NonCommercial will not happen.

This has too many problems due to NonCommercial being not properly legally defined.

When you make a mapping competition with prices it could be already violating the non-commercial aspect depending on which lawyer you ask so this is all highly problematic.

Just look at the RPG Atelier CC-BY-SA-NC ORTP: Nobody can use this because of this terrible license.
